#!/bin/bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_NAME="OpenCodeRemote"

echo "==> OpenCode Remote — Xcode Project Generator"
echo ""

# ─── 1. XcodeGen configuration ──────────────────────────────────────────────

# We prefer XcodeGen over swift package generate-xcodeproj because SPM's
# generator doesn't handle Info.plist, asset catalogs, or build settings well.
# XcodeGen reads a YAML spec and produces a first-class .xcodeproj.

if ! command -v xcodegen &>/dev/null; then
    echo "[!] xcodegen not found. Attempting swift package generate-xcodeproj as fallback..."
    cd "$PROJECT_DIR"

    if swift package generate-xcodeproj 2>/dev/null; then
        echo "[+] Generated: $PROJECT_NAME.xcodeproj"
    else
        echo ""
        echo "[!] swift package generate-xcodeproj failed or is unavailable."
        echo "    Please install XcodeGen and re-run this script:"
        echo "        brew install xcodegen"
        echo ""
        echo "    Manual setup instructions are in README.md."
        exit 1
    fi

    # Post-generation tweaks (optional)
    echo "[*] Opening project — add the scheme manually if needed."
    open "$PROJECT_NAME.xcodeproj" 2>/dev/null || true
    exit 0
fi

# ─── 2. Provisioning profiles / signing ─────────────────────────────────────

if [ -z "${DEVELOPMENT_TEAM:-}" ]; then
    if [ -f ~/.config/opencode/xcode.env ]; then
        source ~/.config/opencode/xcode.env
    fi
fi

TEAM_ID="${DEVELOPMENT_TEAM:-}"
BUNDLE_ID="${BUNDLE_ID:-io.opencode.remote}"
APP_VERSION="${APP_VERSION:-1.0.0}"
BUILD_NUMBER="${BUILD_NUMBER:-1}"

cat > "$PROJECT_DIR/project.yml" << YAMLEOF
name: $PROJECT_NAME
options:
  bundleIdPrefix: io.opencode
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ${TEAM_ID}
    VERSIONING_SYSTEM: apple-generic
    CURRENT_PROJECT_VERSION: ${BUILD_NUMBER}
    MARKETING_VERSION: ${APP_VERSION}
    SWIFT_VERSION: 5.9
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
    DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

targets:
  OpenCodeRemote:
    type: framework
    # Nel progetto Xcode il framework è iOS-only (serve l'app iPhone); la
    # build macOS resta disponibile via SwiftPM (swift build / swift test).
    platform: iOS
    sources:
      - path: Sources/OpenCodeRemote
    dependencies:
      - package: swift-tagged
        product: Tagged
      - package: swift-identified-collections
        product: IdentifiedCollections
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}.sdk
        SKIP_INSTALL: "YES"
        GENERATE_INFOPLIST_FILE: "YES"

  OpenCodeRemoteApp:
    type: application
    # App iOS-only (l'obiettivo è il dispositivo iPhone); un eventuale target
    # macOS si aggiunge separatamente se servirà.
    platform: iOS
    sources:
      - path: Sources/OpenCodeRemoteApp
    dependencies:
      - target: OpenCodeRemote
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_ID}
        INFOPLIST_FILE: Sources/OpenCodeRemoteApp/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"

packages:
  swift-tagged:
    url: https://github.com/pointfreeco/swift-tagged
    from: 0.10.0
  swift-identified-collections:
    url: https://github.com/pointfreeco/swift-identified-collections
    from: 1.0.0

# Scheme — auto-generated by XcodeGen
schemes:
  OpenCodeRemoteApp:
    build:
      targets:
        OpenCodeRemoteApp: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
YAMLEOF

echo "[+] Generated project.yml (XcodeGen spec)"

# ─── 3. Generate .xcodeproj ────────────────────────────────────────────────

cd "$PROJECT_DIR"
xcodegen generate
echo "[+] Generated: $PROJECT_NAME.xcodeproj"

# ─── 4. Open in Xcode ──────────────────────────────────────────────────────

if [ -z "${CI:-}" ]; then
    echo "[*] Opening Xcode..."
    open "$PROJECT_NAME.xcodeproj"
fi

echo ""
echo "==> Done."
echo "    Target:  OpenCodeRemoteApp"
echo "    Bundle:  ${BUNDLE_ID}"
echo "    Version: ${APP_VERSION} (${BUILD_NUMBER})"
echo ""
echo "    To customise signing, set these environment variables:"
echo "        export DEVELOPMENT_TEAM=<your-team-id>"
echo "        export BUNDLE_ID=io.opencode.remote"
